name: Build and Test on Azure as a Static Web App

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      issues: write
      pull-requests: write
    outputs:
      deploy_url: ${{steps.build_site.outputs.static_web_app_url}}
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build And Deploy
        id: build_site
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_CLIFF_0F44EC203 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" 
          api_location: "api"
          output_location: "dist"

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The build works! You can view the deploy preview at ${{steps.build_site.outputs.static_web_app_url}}'
            })

  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v3

      - name: Install Packages
        run: npm run ci

      - name: Percy Test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npx @percy/cli snapshot tests/vr/snapshots.yml --base-url ${{ needs.build.outputs.deploy_url }}

      - name: Run Playwright tests
        run: npm run test:ui:ci
        env:
          SITE_URL: ${{ needs.build.outputs.deploy_url }}

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: tests/ui/results/reports/
          retention-days: 30